services:
  hi-events-frontend:
    build:
      context: ./../../frontend
      dockerfile: Dockerfile.ssr
    container_name: hi-events-frontend
    ports:
      - "8125:80"
    env_file:
      - .env